### ISSUE TITLE
aae-export is not working in blender 4.2

### ISSUE THREAD

**Issue by scrpr** [Akatmks/Akatsumekusa-Aegisub-Scripts#1]
When I try to use aae-export in blender 4.2, it returns error as below:
```
Python: Traceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\aae-export.py", line 4934, in execute
    clip_settings = context.edit_movieclip.AAEExportSettingsClip
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Context' object has no attribute 'edit_movieclip'
```

**Comment by TheOneric** [comment]
fwiw basic plane and tracker export worked for me with

- aae-export as of dec178a46eb16f6f7807d854a2d98156d7d5564c
- Blender 4.2.0
- Windows 10 10.0.19044-SP0
- Python 3.11.7

**Comment by Akatmks** [comment]
Sorry I've been inactive in the year. I should have spend even a tiny little bit of time here so I can catch up with the issues.

The legacy export method through „File > Export“ is not longer recommended (and apparently very badly maintained indeed). Please consider using the new export methods explained in the [docs](https://github.com/Akatmks/Akatsumekusa-Aegisub-Scripts/blob/master/docs/aae-export-tutorial.md#tutorial-2-basic-motion-tracking).
